spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/awsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true